### ISSUE TITLE
database fail

### ISSUE THREAD

**Issue by dustyraven** [fedecarg/webpy-mvc#4]
in every interaction with database, I receive following error:

File "webpy-mvc-master/src/vendor/orm/activerecord.py", line 230, in **init**
    self.Meta.data.new(data)
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by fedecarg** [comment]
Yes, the orm module is still work in progress, sorry. I'll try to fix it during the weekend.

**Comment by dustyraven** [comment]
Thank you. Great work! Exactly what I needed ;)
I'll try to collaborate with whatever I can.
